### ISSUE TITLE
NameError: name 'init' is not defined. Did you mean: 'int'?

### ISSUE THREAD

**Issue by julianogimenez** [new92/IGFollowersIncreaser#19]
Im getting this message.

NameError: name 'init' is not defined. Did you mean: 'int'?

**Comment by new92** [comment]
Hey there, ok so I suppose that you used the version 3 of the script (mainV3.py). There was a bug in the installation process which was causing this error. I've made some changes so now it shouldn't display this error. Please uninstall the script manually and repeat the installation process. It should work fine now. If you have any other troubles feel free to contact me again anytime !
