### ISSUE TITLE
NameError: name 'colorama' is not defined

### ISSUE THREAD

**Issue by julianogimenez** [new92/IGFollowersIncreaser#21]
Traceback (most recent call last):
  File "C:\dev\py\IGFollowersIncreaser\InstagramFollowers\V3\mainV3.py", line 101, in <module>
    elif platform.system() == 'Windows':
         ^^^^^^^^
NameError: name 'platform' is not defined

**Comment by julianogimenez** [comment]
keep eceiving.

PS C:\dev\py\IGFollowersIncreaser\InstagramFollowers\v3> type requirements.txt
instagrapi == 1.16.17
requests == 2.31.0
instaloader == 4.9.5
colorama == 0.4.6
tqdm == 4.65.0
platform == 1.0.8
PS C:\dev\py\IGFollowersIncreaser\InstagramFollowers\v3> pip3 install platform
**ERROR: Could not find a version that satisfies the requirement platform (from versions: none)
ERROR: No matching distribution found for platform**
PS C:\dev\py\IGFollowersIncreaser\InstagramFollowers\v3>

**Comment by new92** [comment]
Ok I changed the script again please check now and if you keep getting this error check if the modules have been installed correctly

**Comment by julianogimenez** [comment]
Hello new92:

![image](https://github.com/new92/IGFollowersIncreaser/assets/2743267/b438800d-ce20-4cae-9f48-a109af9358fc)

**Comment by julianogimenez** [comment]
Hello new92, that works now, but receiving this message:

![image](https://github.com/new92/IGFollowersIncreaser/assets/2743267/2d61f45d-b406-49fd-90d5-97349758f660)

**Comment by new92** [comment]
Great ! Ok so the 429 status code indicates that there have been sent (from the client) many requests. But it's just a warning. The second message (the challenge code by email) means that you need to enter the 6-digit code which has been sent to the email in which is registered the account.
