### ISSUE TITLE
bro what is this use chatgpt to make the readme good 

### ISSUE THREAD

**Issue by dexjr** [new92/IGFollowersIncreaser#27]
[*] Acceptable answers: [True/False]
[?] Keep log ? True
[*] Acceptable answers: [yes/no]
[>] Do you consent that the author (new92) has no responsibility for any loss or damage may the script cause to the given (Instagram) account ? yes
[+] The login credentials will not be stored or saved
|--------------------|LOGIN|--------------------|
[>] Please enter your username: ayxxn.shxrif
[*] Acceptable answers: [yes/no]
[?] The script will increase the followers for the user: ayxxn.shxrif is that correct ? yes
[*] Acceptable answers: [yes/no]
[?] Do you want to grant access to the script to have access to the number of your followers in order to provide additional information ? yes

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=ayxxn.shxrif to https://i.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/

HTTP redirect from https://i.instagram.com/api/v1/users/web_profile_info/?username=ayxxn.shxrif to https://www.instagram.com/accounts/login/?next=/api/v1/users/web_profile_info/
Traceback (most recent call last):
  File "/workspaces/github-follow-bot/IGFollowersIncreaser/InstagramFollowers/V3/mainV3.py", line 872, in <module>
    main()
  File "/workspaces/github-follow-bot/IGFollowersIncreaser/InstagramFollowers/V3/mainV3.py", line 771, in main
    main()
  File "/workspaces/github-follow-bot/IGFollowersIncreaser/InstagramFollowers/V3/mainV3.py", line 451, in main
    profile = instaloader.Profile.from_username(loader.context, username)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/instaloader/structures.py", line 704, in from_username
    profile._obtain_metadata()  # to raise ProfileNotExistsException now in case username is invalid
  File "/home/codespace/.python/current/lib/python3.10/site-packages/instaloader/structures.py", line 773, in _obtain_metadata
    metadata = self._context.get_iphone_json(f'api/v1/users/web_profile_info/?username={self.username}',
  File "/home/codespace/.python/current/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 488, in get_iphone_json
    return self.get_json(path, params, 'i.instagram.com', tempsession)
  File "/home/codespace/.python/current/lib/python3.10/site-packages/instaloader/instaloadercontext.py", line 336, in get_json
    raise LoginRequiredException("Redirected to login page. Use --login.")
instaloader.exceptions.LoginRequiredException: Redirected to login page. Use --login.

**Comment by new92** [comment]
Hey Ayaan, so in order to resolve this issue you need to login from the account you want to increase the followers, follow the instagram instructions to verify that the account belongs to you and execute the script again. If you have already done this and you keep getting this error please reply to this comment.

**Comment by dexjr** [comment]
how to login? u dint mention anything in the readme

**Comment by new92** [comment]
Ok so I mention this error in the [https://github.com/new92/IGFollowersIncreaser/blob/main/README.md#faq-](FAQ) section in the README. You login to your instagram account from your device (phone, laptop, tablet etc.) where you open the Instagram app, enter your credentials (username, password) and follow the instructions to verify that the acc belongs to you. Once you do that you can run the script again and it should work completely fine.

**Comment by dexjr** [comment]
btw does this script uses the browser to get the login credentials.... so it means the script has the acces to my browser right using webdriver i geuss...

**Comment by new92** [comment]
No it doesn't "get" the login credentials, the user enters them. Which version of the script you using ?
