### ISSUE TITLE
Minor errors after V3 update

### ISSUE THREAD

**Issue by brxndonroux** [new92/IGFollowersIncreaser#31]
![image](https://github.com/new92/IGFollowersIncreaser/assets/103594572/fbd4569b-adb2-423a-9ba4-d2b5266883d2)

**Comment by new92** [comment]
Hey @brxndonroux ! In which version of the script are you getting this error ?

**Comment by brxndonroux** [comment]
V3

**Comment by new92** [comment]
Ok let me check it and I'll come back to you. Have you made any changes on the script ? If yes can you mention them ? (In order to help me find the bug).

**Comment by brxndonroux** [comment]
that error is fixed but i have a new one, first i thought my username was spelled wrong but ive tried it multiple times and im still getting this error...looks like its having trouble logging in

![image](https://github.com/new92/IGFollowersIncreaser/assets/103594572/ef9ffe6c-c01e-486e-9c62-a2acd1d27560)

**Comment by new92** [comment]
Hey @brxndonroux ! Ok first things first thanks for the mention (the second photo) I'll change it rightaway ! As for the error you're getting it's just a standard error. Try logging in to your account from a mobile device, follow the steps to verify that the account belongs to you and run again the script !

**Comment by brxndonroux** [comment]
so it still gives me the login error after i did what you said but ill wait a few days and see if it works

Thanks for the support!
