### ISSUE TITLE
stat: path should be string, bytes, os.PathLike or interger, not NoneType

### ISSUE THREAD

**Issue by zackfair1412** [new92/IGFollowersIncreaser#32]
**Describe the bug**

**To Reproduce**
1. Go to V3 folder & run the script
2. put the 'yes' input when the 2nd question pop-up
3. See error --> stat: path should be string, bytes, os.PathLike or interger, not NoneType

**Expected behavior**
i can run the script as per said

**Screenshots**
![image](https://github.com/new92/IGFollowersIncreaser/assets/27601824/bc803f09-d6bd-4378-afed-3cf571b18798)

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser: None (cmd in window)
 - Version V3

**Additional context**

**Comment by new92** [comment]
Hey @zackfair1412, ok so I changed the code. Try now and if it runs again in an error please mention it here. If you don't get one also mention it so I can close this issue.

**Comment by zackfair1412** [comment]
yes, that work. thank you

**Comment by new92** [comment]
Great ! Glad I helped !
