### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Kekkerons** [new92/IGFollowersIncreaser#36]
Hi, since last week i got this error, i tried with all 3 versions, did few tests but it doesn't work.
I need help with that.
![Screenshot 2023-09-04 203022](https://github.com/new92/IGFollowersIncreaser/assets/120341729/7ec8b85d-58ad-40b3-a373-96d70c9dce12)

**Comment by new92** [comment]
Ok so the specific error indicates that you should wait a few minutes before using the script again. But since it has been a week then I recommend to either delete and reinstall the script or try with another account. If you've made any changes to the script's code try removing them and trying again

**Comment by Kekkerons** [comment]
Ok, i tried deleting/reinstalling the script and i still got errors (i didn't edit the script)
Tried the 3 versions with different accounts.
![Screenshot 2023-09-04 203022](https://github.com/new92/IGFollowersIncreaser/assets/120341729/6a1b75e8-80c0-40a1-ab80-07ad99af0c90)
![Screenshot 2023-09-05 232153](https://github.com/new92/IGFollowersIncreaser/assets/120341729/b70a26a3-8dc7-4edd-afdd-f7bb480ff087)
![Screenshot 2023-09-05 232655](https://github.com/new92/IGFollowersIncreaser/assets/120341729/2f708d64-0dac-40cd-82e2-bea76a873937)
![Screenshot 2023-09-05 233010](https://github.com/new92/IGFollowersIncreaser/assets/120341729/0c9bda65-04da-4c67-bca1-d3e10ee7fbf9)

**Comment by new92** [comment]
Ok so in the last 2 pictures what the error mean is that you have to login to your account and follow the verification steps. In the first 2 pictures it's a bug in the code which I'm planning to fix asap.

**Comment by Kekkerons** [comment]
Alright, thanks. I'll wait the fix and let you know if the error persists

**Comment by new92** [comment]
Great !
